name: alarmcat
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_slidable: ^3.1.0
  sqflite: ^2.4.2
  google_fonts: ^6.2.1
  sqflite_common_ffi: ^2.3.6
  vibration: ^3.1.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
